# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - vault-warden

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Log in to registry
      uses: docker/login-action@v1
      with:
        registry: https://mcr.microsoft.com/
        username: ${{ secrets.AzureAppService_ContainerUsername_fa2112b1c8204a9aa25abac156a182e2 }}
        password: ${{ secrets.AzureAppService_ContainerPassword_170eaf6a410c457389f97d09a5aa4c40 }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v2
      with:
        push: true
        tags: mcr.microsoft.com/${{ secrets.AzureAppService_ContainerUsername_fa2112b1c8204a9aa25abac156a182e2 }}/appsvc/staticsite:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'vault-warden'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_bbf186afc6af4dfda05558964456c3b3 }}
        images: 'mcr.microsoft.com/${{ secrets.AzureAppService_ContainerUsername_fa2112b1c8204a9aa25abac156a182e2 }}/appsvc/staticsite:${{ github.sha }}'